# name: test
# Fill in the necessary code to run the jest test script whenever a pull request is opened or updated    

name: test 
on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: node 18.x
        uses: actions/setup-node@v2
        with:
            node-version: 18.x

      - name: install dependencies
        run: npm ci

      - name: test
        run: npm run test
